### ISSUE TITLE
Light mode / Dark mode doesn't get saved

### ISSUE THREAD

**Issue by TetrisIQ** [TetrisIQ/poll-dapp#6]
**Describe the bug**
The light mode and dark mode switch resets on every page reload. 

**Expected behavior**
If I choose dark mode and refresh the page. The Page should have dark mode enabled. 

**Additional context**
This is not implemented for now.

> The switch can be replaced with a better working one.

**Comment by TetrisIQ** [comment]
Hey, 
The toggle is located under [src/lib/ToggleDarkMode.svelte](https://github.com/TetrisIQ/poll-dapp/blob/0e935b3aa7363daa182df39b36640bbaccff3d0c/src/lib/ToggleDarkMode.svelte).  
You can also check out [src/gun/LStore.ts](https://github.com/TetrisIQ/poll-dapp/blob/0e935b3aa7363daa182df39b36640bbaccff3d0c/src/gun/LStore.ts) which is a wrapper around the local storage. 

Some helpful links for learning svelte
> https://www.youtube.com/watch?v=rv3Yq-B8qp4
> https://svelte.dev/tutorial/basics

**Comment by npiyush97** [comment]
Lot of code which do not adhere to dry code .
